//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.239
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Willcraftia.Xna.Blocks.BlockViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Willcraftia.Xna.Blocks.BlockViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CameraModeButton {
            get {
                return ResourceManager.GetString("CameraModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close LoD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseLodWindowButton {
            get {
                return ResourceManager.GetString("CloseLodWindowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultButton {
            get {
                return ResourceManager.GetString("DefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnButton {
            get {
                return ResourceManager.GetString("EnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   にほんご に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JaButton {
            get {
                return ResourceManager.GetString("JaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoD: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LevelOfDetailLabel {
            get {
                return ResourceManager.GetString("LevelOfDetailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light #0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Light0Button {
            get {
                return ResourceManager.GetString("Light0Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light #1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Light1Button {
            get {
                return ResourceManager.GetString("Light1Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light #2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Light2Button {
            get {
                return ResourceManager.GetString("Light2Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LightModeButton {
            get {
                return ResourceManager.GetString("LightModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LightModeTitle {
            get {
                return ResourceManager.GetString("LightModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadFileButton {
            get {
                return ResourceManager.GetString("LoadFileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Menu ([Y] key) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenuButton {
            get {
                return ResourceManager.GetString("MainMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No file exists in your storage. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoFileError {
            get {
                return ResourceManager.GetString("NoFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to load this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenFileConfirmation {
            get {
                return ResourceManager.GetString("OpenFileConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectLanguageButton {
            get {
                return ResourceManager.GetString("SelectLanguageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectLanguageTitle {
            get {
                return ResourceManager.GetString("SelectLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show LoD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowLodWindowButton {
            get {
                return ResourceManager.GetString("ShowLodWindowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
    }
}
