//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.261
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Willcraftia.Xna.Blocks.BlockViewer.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Willcraftia.Xna.Blocks.BlockViewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Agree に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AgreeButton {
            get {
                return ResourceManager.GetString("AgreeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authorized に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AuthorizedButton {
            get {
                return ResourceManager.GetString("AuthorizedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Back に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Box connection failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxConnectionFailedMessage {
            get {
                return ResourceManager.GetString("BoxConnectionFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you authorized this application on Box website, please select [Authorized] button that will try to access your Box account from this application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizAccessAccountMessage {
            get {
                return ResourceManager.GetString("BoxWizAccessAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access Your Box Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizAccessAccountTitle {
            get {
                return ResourceManager.GetString("BoxWizAccessAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To use this function, you must setup Box (http://www.box.com) integration on this application. This setup will requires to access Box and your account on it via the Internet.
        ///
        ///If you allow that, select [Agree] button after signed up for Box, otherwise [Cancel]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizAttentionMessage {
            get {
                return ResourceManager.GetString("BoxWizAttentionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Attention に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizAttentionTitle {
            get {
                return ResourceManager.GetString("BoxWizAttentionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now, this application obtained permission to use Box, but can not access your Box account yet.  To do it, this application must be authorized by you on Box website.
        ///
        ///Please select [Launch web browser] button that will open your web browser and forward the authorization page on Box. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizAuthorizationMessage {
            get {
                return ResourceManager.GetString("BoxWizAuthorizationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authorization に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizAuthorizationTitle {
            get {
                return ResourceManager.GetString("BoxWizAuthorizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connecting to Box... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizConnectingMessage {
            get {
                return ResourceManager.GetString("BoxWizConnectingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All settings to use Box integration are finished.
        ///
        ///Please select [Upload] button if you want to upload demo Blocks meshes in your Box, otherwise [Cancel]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizFinishMessage {
            get {
                return ResourceManager.GetString("BoxWizFinishMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Box Setup Finished に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizFinishTitle {
            get {
                return ResourceManager.GetString("BoxWizFinishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This application could access your Box account successfully !
        ///
        ///Next, the folder named &apos;Blocks Home&apos; to upload Blocks&apos;s data is needed on your Box.
        ///
        ///Please select [Create] button if you allow to create this folder on you Box, otherwise [Cancel]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizPrepareFolderTreeMessage {
            get {
                return ResourceManager.GetString("BoxWizPrepareFolderTreeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Prepare Folders for Blocks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizPrepareFolderTreeTitle {
            get {
                return ResourceManager.GetString("BoxWizPrepareFolderTreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This application created &apos;Blocks Home&apos; folder in your Box.
        ///
        ///You can save this settings on your storage. If you don&apos;t save it, you will lost it after this application exit.
        ///
        ///Please select [Yes] button if you want to save this settings, otherwise [No]. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizSaveSettingsMessage {
            get {
                return ResourceManager.GetString("BoxWizSaveSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizSaveSettingsTitle {
            get {
                return ResourceManager.GetString("BoxWizSaveSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving your Box settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizSavingSettingsMessage {
            get {
                return ResourceManager.GetString("BoxWizSavingSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try to access to your Box account... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizTryAccessAccountMessage {
            get {
                return ResourceManager.GetString("BoxWizTryAccessAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Try to prepare folders in your Box... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BoxWizTryPrepareFoldersMessage {
            get {
                return ResourceManager.GetString("BoxWizTryPrepareFoldersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Camera に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CameraModeButton {
            get {
                return ResourceManager.GetString("CameraModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking your Box settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CheckingBoxSettingsMessage {
            get {
                return ResourceManager.GetString("CheckingBoxSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultButton {
            get {
                return ResourceManager.GetString("DefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Demo blocks have been installed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DemoBlocksInstalledInformation {
            get {
                return ResourceManager.GetString("DemoBlocksInstalledInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Demo blocks have been uploaded to your Box. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DemoBlocksUploadedInformation {
            get {
                return ResourceManager.GetString("DemoBlocksUploadedInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Diffuse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DiffuseColorLabel {
            get {
                return ResourceManager.GetString("DiffuseColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EnButton {
            get {
                return ResourceManager.GetString("EnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Grid View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GridViewModeButton {
            get {
                return ResourceManager.GetString("GridViewModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HideButton {
            get {
                return ResourceManager.GetString("HideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install Demo Blocks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InstallDemoBlocksButton {
            get {
                return ResourceManager.GetString("InstallDemoBlocksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to install demo blocks to your storage ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InstallDemoBlocksConfirmation {
            get {
                return ResourceManager.GetString("InstallDemoBlocksConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   にほんご に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string JaButton {
            get {
                return ResourceManager.GetString("JaButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Launch web browser に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LaunchWebBrowserButton {
            get {
                return ResourceManager.GetString("LaunchWebBrowserButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoD: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LevelOfDetailLabel {
            get {
                return ResourceManager.GetString("LevelOfDetailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light #0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Light0ModeButton {
            get {
                return ResourceManager.GetString("Light0ModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light #0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Light0Title {
            get {
                return ResourceManager.GetString("Light0Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light #1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Light1ModeButton {
            get {
                return ResourceManager.GetString("Light1ModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light #1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Light1Title {
            get {
                return ResourceManager.GetString("Light1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light #2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Light2ModeButton {
            get {
                return ResourceManager.GetString("Light2ModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light #2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Light2Title {
            get {
                return ResourceManager.GetString("Light2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   List View に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ListViewModeButton {
            get {
                return ResourceManager.GetString("ListViewModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadButton {
            get {
                return ResourceManager.GetString("LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LodButton {
            get {
                return ResourceManager.GetString("LodButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   LoD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LodMenuTitle {
            get {
                return ResourceManager.GetString("LodMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Menu ([Y] key) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenuButton {
            get {
                return ResourceManager.GetString("MainMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModeButton {
            get {
                return ResourceManager.GetString("ModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModeMenuTitle {
            get {
                return ResourceManager.GetString("ModeMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to load this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenFileConfirmation {
            get {
                return ResourceManager.GetString("OpenFileConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectLanguageButton {
            get {
                return ResourceManager.GetString("SelectLanguageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectLanguageTitle {
            get {
                return ResourceManager.GetString("SelectLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowButton {
            get {
                return ResourceManager.GetString("ShowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort by Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortByColorButton {
            get {
                return ResourceManager.GetString("SortByColorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort by Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SortByNameButton {
            get {
                return ResourceManager.GetString("SortByNameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specular に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SpecularColorLabel {
            get {
                return ResourceManager.GetString("SpecularColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn off a light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TurnOffLightButton {
            get {
                return ResourceManager.GetString("TurnOffLightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Turn on a light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TurnOnLightButton {
            get {
                return ResourceManager.GetString("TurnOnLightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UploadButton {
            get {
                return ResourceManager.GetString("UploadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload Demo Blocks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UploadDemoBlocksButton {
            get {
                return ResourceManager.GetString("UploadDemoBlocksButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to upload demo meshes to your Box ? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UploadDemoBlocksConfirmation {
            get {
                return ResourceManager.GetString("UploadDemoBlocksConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload demo blocks to your Box failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UploadDemoBlocksToBoxFailedMessage {
            get {
                return ResourceManager.GetString("UploadDemoBlocksToBoxFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uploading demo mesh files to your Box... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UploadingDemoBlocksMessage {
            get {
                return ResourceManager.GetString("UploadingDemoBlocksMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
